-- ══════════════════════════════════════════════════════════════
-- AI Running Coach System
-- ══════════════════════════════════════════════════════════════

-- 1. Runner coaching profile (onboarding data + assessment)
CREATE TABLE IF NOT EXISTS public.coach_profiles (
  user_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  goal text NOT NULL DEFAULT 'consistencia', -- comecar, pace, prova, consistencia
  race_distance text, -- 5k, 10k, 21k, 42k
  race_date date,
  days_per_week int NOT NULL DEFAULT 3,
  current_pace_seconds int, -- seconds per km
  injury_history text,
  level text DEFAULT 'iniciante', -- zero, iniciante, intermediario, avancado
  vdot numeric DEFAULT 0,
  zones jsonb, -- { E: {min, max}, M: {pace}, T: {pace}, I: {pace}, R: {pace} }
  plan_total_weeks int DEFAULT 12,
  plan_current_week int DEFAULT 1,
  plan_phase text DEFAULT 'base', -- base, construcao, especifico, taper, recuperacao
  plan_started_at timestamptz DEFAULT now(),
  last_assessment_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.coach_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own coach profile" ON public.coach_profiles
  FOR ALL USING (auth.uid() = user_id);

-- 2. Weekly plans (generated by AI)
CREATE TABLE IF NOT EXISTS public.coach_weekly_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  week_number int NOT NULL,
  phase text NOT NULL, -- base, construcao, especifico, taper
  volume_target_km numeric NOT NULL DEFAULT 0,
  days jsonb NOT NULL, -- array of DayPlan objects
  ai_notes text, -- coach message for the week
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.coach_weekly_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own plans" ON public.coach_weekly_plans
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Insert own plans" ON public.coach_weekly_plans
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE INDEX idx_coach_plans_user_week ON public.coach_weekly_plans (user_id, week_number DESC);

-- 3. Daily workout log (tracks what was prescribed vs done)
CREATE TABLE IF NOT EXISTS public.coach_workout_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  plan_id uuid REFERENCES public.coach_weekly_plans(id) ON DELETE SET NULL,
  day_of_week text NOT NULL, -- segunda, terca, etc
  prescribed_type text, -- easy, interval, long, tempo, etc
  prescribed_distance_km numeric,
  prescribed_pace text,
  actual_distance_km numeric,
  actual_pace text,
  actual_time_seconds int,
  rpe int, -- 1-5 (como se sentiu)
  status text DEFAULT 'pending', -- pending, completed, skipped
  completed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.coach_workout_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own workout log" ON public.coach_workout_log
  FOR ALL USING (auth.uid() = user_id);

CREATE INDEX idx_coach_log_user ON public.coach_workout_log (user_id, created_at DESC);

-- 4. Coach chat history
CREATE TABLE IF NOT EXISTS public.coach_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  role text NOT NULL, -- user, assistant
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.coach_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own messages" ON public.coach_messages
  FOR ALL USING (auth.uid() = user_id);

CREATE INDEX idx_coach_messages_user ON public.coach_messages (user_id, created_at DESC);

-- 5. Weekly summary (generated after each week)
CREATE TABLE IF NOT EXISTS public.coach_weekly_summaries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  week_number int NOT NULL,
  volume_target_km numeric,
  volume_done_km numeric,
  completion_pct numeric,
  workouts_done int,
  workouts_total int,
  avg_rpe numeric,
  pace_trend text, -- improving, stable, declining
  avg_pace_seconds int,
  message text, -- AI generated summary
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.coach_weekly_summaries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own summaries" ON public.coach_weekly_summaries
  FOR SELECT USING (auth.uid() = user_id);

-- 6. RPC: Get full coach context for a user (for AI prompt)
CREATE OR REPLACE FUNCTION get_coach_context(p_user_id uuid)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_profile record;
  v_plan jsonb;
  v_recent_runs jsonb;
  v_recent_log jsonb;
  v_last_summary jsonb;
BEGIN
  -- Coach profile
  SELECT * INTO v_profile FROM coach_profiles WHERE user_id = p_user_id;

  -- Current week plan
  SELECT to_jsonb(p) INTO v_plan
  FROM coach_weekly_plans p
  WHERE user_id = p_user_id
  ORDER BY week_number DESC LIMIT 1;

  -- Last 8 weeks of runs (from strava_awarded_runs)
  SELECT jsonb_agg(row_to_json(r)) INTO v_recent_runs FROM (
    SELECT activity_date, distance_km, moving_time_seconds,
      ROUND(moving_time_seconds / NULLIF(distance_km, 0))::int AS pace_seconds_per_km
    FROM strava_awarded_runs
    WHERE user_id = p_user_id
    ORDER BY activity_date DESC
    LIMIT 30
  ) r;

  -- Recent workout log (last 2 weeks)
  SELECT jsonb_agg(row_to_json(l)) INTO v_recent_log FROM (
    SELECT day_of_week, prescribed_type, prescribed_distance_km,
      actual_distance_km, actual_pace, rpe, status, completed_at
    FROM coach_workout_log
    WHERE user_id = p_user_id AND created_at >= now() - interval '14 days'
    ORDER BY created_at DESC
  ) l;

  -- Last weekly summary
  SELECT to_jsonb(s) INTO v_last_summary FROM (
    SELECT week_number, volume_target_km, volume_done_km, completion_pct,
      pace_trend, message
    FROM coach_weekly_summaries
    WHERE user_id = p_user_id
    ORDER BY week_number DESC LIMIT 1
  ) s;

  RETURN json_build_object(
    'profile', CASE WHEN v_profile IS NOT NULL THEN row_to_json(v_profile) ELSE NULL END,
    'current_plan', v_plan,
    'recent_runs', COALESCE(v_recent_runs, '[]'::jsonb),
    'recent_log', COALESCE(v_recent_log, '[]'::jsonb),
    'last_summary', v_last_summary
  );
END; $$;
